WEBHOOK_PASSPHRASE = "123456"

API_KEY = 'OgOpidGBbcDvLzmF8fj8SHv4wdMpjlhiBLOQUyahrRf9eNtnPZEwwgHq1ky1sJmK'
API_SECRET = 'GMx0IQZOP0arEnHxay1bTSUddzLPE5gFLmscJJqitwXLKpuVgmCnm5NBvUzldNh1'

key = 'OgOpidGBbcDvLzmF8fj8SHv4wdMpjlhiBLOQUyahrRf9eNtnPZEwwgHq1ky1sJmK'
secret = 'GMx0IQZOP0arEnHxay1bTSUddzLPE5gFLmscJJqitwXLKpuVgmCnm5NBvUzldNh1'